Health-Education-England/TIS-TCS

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonValidatorTest.java
1. When creating a Person from UI or bulk upload, check if the Role in the DTO is empty. -- `checkMandatoryFields()`
2. When updating a Person from bulk upload, If the Role in the DTO is empty, check the role of the entity in the DB exists. -- `isUpdatable()`
3. Check if the Role matches Reference data. -- `checkRole()`
TIS21-1752
=> feat: check Role mandatory for Person Create/Update

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PersonResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonValidatorTest.java
**TIS21-1629: Update bulk person create to validate and set the role correctly**
Make checkRole() in PersonValidator use the new endpoint from REFERENCE that returns a Map<String,String> instead of a
Map<String,Boolean>.
E.G.:
- role `dr in training` is passed in
- the `/roles/matches/` Reference endpoint will return a Map like: { "dr in training" : "DR in Training" }.
- the value (retrieved from the DB, therefore correctly cased) is used to set `personDto.role()`
~~As highlighted in the Reference PR, the naming still needs to be standardized (i.e. we're no longer just checking that a role exists but we're kinda checking for matches, so the method and the collections will have to reflect that)~~ (I think I tracked down all uses of 'exist' terminology and replaced it with 'match')
~~The …
=> feat: Change PersonValidator

tcs-client/pom.xml, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PlacementValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PlacementValidatorTest.java
Make PlacementValidator compare between the new and old NPNs of a Placement in case of Placement update, and return a FieldError in case they're different && EsrEvents are present (i.e. someone's trying to update the NPN of an exported Placement)
**TIS21-174**: Make NPN read-only
=> feat: Add validation to PlacementValidator

.github/workflows/ci-cd-workflow.yml
As published artifacts cannot be overwritten the publish step will fail
unless the version is bumped for all modules. Until we have an automated
way to do this the safer approach is to allow failures to continue to
stop non-versioned chore type PRs from breaking the build (e.g.
Dependabot, documentation and other non-code changes that don't usually
warrant a manual version bump).
TIS21-2495
=> chore: Allow publish artifacts to fail silently

.github/workflows/ci-cd-workflow.yml
When deploying all module with the same command a failure in earlier
modules will cause a later failure. This can not be mitigated by
`--fail-at-end` due to dependencies between the modules.
Without this split then it would never be possible to publish a new
version of `tcs-client` or `tcs-persistence` unless `tcs-api` is also
bumped and published.
TIS21-2495
=> chore: split deployments so failures don't cascade

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/PlacementServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/PlacementServiceImplTest.java
When updating the `wte` in a placement, backend calls a `isEligibleForCurrentTraineeWteChangeNotification` method which compares if the current `wte` and the new `wte` are the same. If the current `wte` is null, it throws a NPE, which results in a 500 error on the UI.
TIS21-2441
=> fix: NPE in isEligibleForCurrentTraineeWteChangeNotification method

.github/workflows/ci-cd-workflow.yml
The multiline command still causes cascading failures, split the
commands in to individual steps each with `continue-on-error` set to
true.
TIS21-2495
=> chore: Split multiline cmd to separate steps

tcs-client/pom.xml
Forgot to bump tcs-client version up last time I merged.
Before approving, do I need to bump **tcs-parent-client** too?
=> chore: Update tcs-client version

.aws/tis-tcs-nimdta.json, .aws/tis-tcs-preprod.json, .aws/tis-tcs-prod.json
All environments are using the same task family, so the revisions are a
mix of environments.
Fix this by adding the environment to the task family.
TIS21-SCOUT
=> chore: add environment to task definition family

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidatorTest.java
This makes the email address validation regexp consistent with the one
used in admins-ui.
Note that it is not comprehensive: tests have been enhanced to
demonstrate failing examples. As such, the TODO for finding a better
solution has been left in place.
TIS21-2764
=> fix: email address validation regexp

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java
Prior to making changes to the structure and content of the
ProgrammeMembership table. All interactions should now be with the
CurriculumMembership table.
TIS21-2900
=> feat: stop parallel data writes to PM table

tcs-service/src/main/resources/db/migration/schema/V4.21__refactor_programmeMembership.sql
There are some records with NULL programmeStartDates which broke the
previous flyway V4.21_refactor_programmeMembership.sql script
The new checksum is -541714420
TIS21-2510: Rebuild ProgrammeMembership table and populate
=> fix: NIMDTA-aware Programme Membership refactor

tcs-service/src/main/resources/db/migration/schema/V4.22__update_contactDetails_email.sql
1. emails shouldn't have any non-breaking spaces, so replace all of them with ''
2. the setting 'sql_safe_updates' are off on Stage/Prod/NIMDTA, so it's okay not to have ID in where clause for updates.
3. records affected: Prod: 108, NIMDTA: 4.
TIS21-2866
=> fix: trim and remove all non-breaking spaces in emails

tcs-service/pom.xml, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidatorTest.java
Before we applied the flyway script to fix the email on Prod/NIMDTA, the latest email needed to be fixed had the amendedDate "2021-10-12T14:42:23.155", and we fixed the RegEx of email on 06/04/2022. By adding the tests, I found the whitespaces and non-breaking spaces are already filtered out by the new RegEx.
Besides, according to [Wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space), the non-breaking space in Unicode is `U+00A0`.
TIS21-2866
=> test: add tests for email validation

tcs-client/pom.xml, tcs-client/src/main/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImpl.java, tcs-client/src/test/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImplMockTest.java
Make the returned DTO type consistent with the DTO returned by the API
call.
Note: breaking change to tcs-client.
TIS21-3127: Ensure placement IDs are included in the response from TCS
client
=> fix: getPlacementForTrainee return Dto

tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/ProgrammeMembership.java, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapper.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java
Cause of the bug:
The entities Person and ProgrammeMembership are 1 to many mapping (bidirectional relationship), and when a programmeMembership is deleted from the child side, the deletion doesn't get synchronised to the parent side. 
Some similar discussion can be found here: https://stackoverflow.com/questions/22688402/delete-not-working-with-jparepository
Solutions I can think of and have verified on local:
1. get the changes flushed to the DB before populating personStatus, so that (I think) the cached person object will get updated.
2. add a `@PreRemove` hook to dimiss the parent before the child programmeMembership is deleted.
I've chosen the 2nd solution as it doesn't break the transaction itself and solves the real problem.
TIS21-3311
=> fix: get personStatus updated when a programmeMembership is deleted

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResource.java
Description: the AuditingAspect only allows logging for method update/delete/create. So change remove to delete to turn on logging.
There're 2 endpoints in TCS for deleting PM or CM. How are they used by frontend?
TIS frontend sends requests to `@PostMapping("/programme-memberships/delete/")` when deleting a while PM or the last CM under one PM, while sends request to `@DeleteMapping("/programme-memberships/{id}")` when deleting a single CM which is not the only one under the PM.
Logging tested on local.
TIS21-3463
=> fix: audit logging for deleting PM

tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java
I did "EXPLAIN" traineeInfoForConnection.sql, I think the performance are decided by the rows of Person, nested query to get current PMs and nested query to get max CM.
So I tried limiting the query rows of personId to 10000, and the below pics are comparison of EXPLAIN output when I added _where clauses_ in different places:
- Add where clause in `ot` only:
https://build.tis.nhs.uk/metabase/question/474
- Add where clauses in nested queries and Person table:
https://build.tis.nhs.uk/metabase/question/473
We can see the 1st query needs to examine more rows to execute the whole query.
Some docs of "EXPLAIN": https://dev.mysql.com/doc/refman/5.7/en/explain-output.html
TIS21-3229
=> feat: add clauses For Reval Sync Sql

tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationRabbitServiceImpl.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationRabbitServiceImplTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
1. [The commit](https://github.com/Health-Education-England/TIS-TCS/pull/896/commits/a4dd1e1ad2f71f424bada7f2f0184100be266467) which uses alias `personId` for the 3rd where clause doesn't work. (I thought I had tested it very well, but apparently not😢)Because: 
- personId exists in temporary tables `latestCm` and `currentPmCounts`, so it's ambiguous for where clause; 
- MySQL executes where clauses first, then maps aliases, so personId is not available for p.id when where clause is being executed, unless we use `having`. But using `having` means that we will lose the optimisation of the DB and results in bad performance.
2. add macros in the format of `WHERECLAUSE(p, id)` in the SQL, so that we can recognise the macro by RegEx and get the parameters from the macro and populate the real …
=> feat:use RevalSyncSql for Single Person export

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ConnectionInfoToRevalidationRecordMapper.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/RevalidationRecordMapper.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
1. call `buildTcsConnectionInfo` method to use `traineeInfoForConnection.sql` to get ConnectionInfoDto and then map it to RevalidtionRecordDto.
2. use Repositories to get grade of the first current placement. -- I haven't changed logic for this bit, but we allow overlapping placements, not sure if it was discussed to use the first current one.
TIS21-3229
=> fix:buildRevalidationRecord

tcs-service/pom.xml
depend on [TIS-REFERENCE #268](https://github.com/Health-Education-England/TIS-REFERENCE/pull/268)
TIS21-3518
=> chore: bump version of reference-client

tcs-persistence/pom.xml, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/CurriculumMembershipRepository.java, tcs-persistence/src/test/java/com/transformuk/hee/tis/tcs/service/repository/CurriculumMembershipRepositoryIntTest.java, tcs-persistence/src/test/resources/scripts/curriculumMembership.sql, tcs-persistence/src/test/resources/scripts/deleteCurriculumMembership.sql, tcs-service/pom.xml
personId, programme, programmeEndDate etc. should be updated in the
ProgrammeMembership table, and removed from the CurriculumMembership table.
TIS21-2388
=> refactor:CM repository to remove deprecated fields

tcs-persistence/pom.xml, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/ProgrammeMembershipRepository.java, tcs-persistence/src/test/java/com/transformuk/hee/tis/tcs/service/repository/ProgrammeMembershipRepositoryIntTest.java, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/listener/person/TrainingNumberElasticSearchEventListener.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/listener/person/TrainingNumberElasticSearchEventListenerTest.java
The initial refacotring from PM to CM is in this commit: https://github.com/Health-Education-England/TIS-TCS/commit/3fd3540
`TrainingNumber` is deprecated in CM, so we have to change the listener to use PM.
However, there's no entry to modify training numbers on TIS admin UI. And, in tcs-service, I'm not able to find anywhere who sends the `TrainingNumberXXXEvent`. Had a quick discussion with James before, and he also mentioned this functionality would be added in the future.
In this PR, I added a query in `ProgrammeMembershipRepository` as I thought we need it, but the current process doesn't modify the `trainingNumber` in PMs, which needs to be fixed when we start to implement this functionality.
TIS21-2388
=> refactor: trainingNumberEsEventListener to use ProgrammeMembershipRepository.

.aws/tis-tcs-nimdta.json, .aws/tis-tcs-preprod.json, .aws/tis-tcs-prod.json, tcs-api/pom.xml, tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/ConditionsOfJoiningDto.java, tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/enumeration/GoldGuideVersion.java, tcs-client/pom.xml, tcs-persistence/pom.xml, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/ConditionsOfJoining.java, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/ConditionsOfJoiningRepository.java, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/event/ConditionsOfJoiningSignedEvent.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListener.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningService.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ConditionsOfJoiningMapper.java, tcs-service/src/main/resources/config/application-local.yml, tcs-service/src/main/resources/config/application.yml, tcs-service/src/main/resources/db/migration/schema/V4.25__create_conditions_of_joining_table.sql, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListenerTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceTest.java, tcs-service/src/test/resources/config/application.yml, tcs-service/src/test/resources/db/migration/schema/V4.25__create_conditions_of_joining_table.sql
Listener for COJ signed events and persist the `signedAt` timestamp and COJ version against the associated ProgrammeMembership UUID.
Ideally this would be persisted via the ProgrammeMembership itself, however there were issues saving the ProgrammeMembershipDto retrieved from the database.
This approach allows us to capture the signed COJ to avoid losing data, given time to come back and resolve the PM persistence when we add the COJ data to the ProgrammeMembershipDto.
TIS21-4431
TIS21-4375
=> feat: store signed COJ against PM ID

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListener.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListenerTest.java
If a programme is not found for the signed Conditions of Joining an `IllegalArgumentException` is throw. However, this causes the message to be requeued instead of going to the DLQ.
To ensure that the message correctly goes to the DLQ the exception should be caught and rethrown as a `AmqpRejectAndDontRequeueException`.
TIS21-4551
TIS21-4550
=> fix: do not requeue COJ sign event when invalid

tcs-persistence/pom.xml, tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql, tcs-service/pom.xml
TIS21-4555 UNKNOWN doctors should not be in the revalidation system
=> feat: exclude unknown gmc ids from reval sync and cdc

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/RevalidationMessageListener.java
Logs in integration service doesn't refect the real count of how many doctors sent from tcs to Reval.
So add more logging here.
TIS21-4555
=> feat:log for count of doctors sync to Reval

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/event/ConditionsOfJoiningSignedEvent.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListener.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/ConditionsOfJoiningService.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/ProgrammeMembershipService.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImpl.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListenerTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImplTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java
For a limited time, events may include a curriculum membership id (long) as previously, or the new programme membership uuid. The latter will be the only accepted form after the transition period.
TIS21-4660
=> feat: accept CoJ signed events with id or uuid

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapper.java, tcs-service/src/main/resources/config/application-local.yml, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/listener/person/TrainingNumberElasticSearchEventListenerTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapperTest.java
This refactoring is mainly about ProgrammeMembershipMapper:
1. use outside mappers instead of private mapers when possible
2. add more comments, and shorten some method variables to make them more readable
3. in private method `programmeMembershipToProgrammeMembershipDTO`, define an empty curriculumMemberhsip list instead of having to define it in outer layers.
TIS21-2403
=> refactor:programme membership

tcs-client/pom.xml, tcs-client/src/main/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImpl.java, tcs-client/src/test/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImplMockTest.java, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResource.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceTest.java
The GET endpoint for programme memberships currently only support a `Long` id and performs a lookup via CurriculumMembership id, update the endpoint to allow both a `Long` id using the existing behaviour and a `UUID`, which will perform a direct lookup on
`ProgrammeMembership.uuid`.
Add a method to `TcsServiceImpl` to allow calling of the GET endpoint for programme memberships by UUID.
TIS21-4173
TIS21-2399
=> feat: GET programme memberships accepts UUID

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/RevalidationResource.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/RevalidationResourceTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
fix NullPointerException for "/revalidation/trainee/{gmcId}" when gmcId not found in TCS.
TIS21-4548
=> fix:NPE for reval

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/listener/person/CurriculumMembershipEventListener.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/listener/person/CurriculumMembershipEventListenerTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java
In User Research-Revalidation channel, Katy raised a query on 27 June that they updated the programme membership info of a doctor but the doctor was still in the Discrepancy list.
This happened when the curriculum membership was deleted, and no message was sent to Reval to update the programme details.
no-ticket
=> fix:sending CurriculumMembershipDeletedEvent when curriculumMembership is deleted

tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
`personId` will no longer be in CurriculumMembership table.
We have 2 options to fix this in traineeInfoForConnection.sql:
1. just get rid of `WHERECLAUSE(cm, personId)` --> much lower the performance for a single record export (very quickly -> more than 2s)
2. join the ProgrammeMembership table to get personId --> lower the performance for the full sync (at most 2s more than before, and around 10s in total). I think this option is more acceptable.
TIS21-2403
=> fix:use PM.personId for ConnectionInfo

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java
This logging results in many [Sentry errors](https://health-education-england-9v.sentry.io/issues/4263002213/?project=5752964&query=&referrer=project-issue-stream).
Howeve there're always doctors in TIS don't exist in Reval, and we also exclude doctors whose gmc number == "UNKNOWN" or null, so we should remove this error logging.
no-ticket
=> fix:mute unnecessary error for reval data export

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/PersonServiceImpl.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/PlacementRowMapper.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/PostServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java
1. bump version of tcs-client to lower the log level
2.  set null value when real value of getLong() was NULL, including:
-  PersonServiceImpl: mapper is used when `enableES` is false to decorate person views in the person list. As `enableES` is true in every environment, so I think this is not used, but it's a better-to-fix
- PlacementRowMapper: mapper is used in Peron details -> Placement Summary list. This fix will affect the UI:
Before (currently on Prod): 
After (tested locally):
As shown above, "0" site id will be removed from the placement summary list, leaving a pair of brackets there.
- PostViewRowMapper: mapper is used in PostView list. The fix will remove all "0" values from the parameters in the request to get the reference data, and it doesn't affect the UI.
- …
=> fix:set null values when last ResultSet col was null and bump verison of tcs-client

tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql
Given that a doctor has a Person Role like ‘%Placeholder%’ or like ‘%Dummy%’
When Reval admin visits the discrepancies  page
Then they should NOT see that doctor
TIS21-4690
=> feat: filter dummy trainee role

tcs-api/pom.xml, tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/ConditionsOfJoiningDto.java, tcs-client/pom.xml, tcs-persistence/pom.xml, tcs-service/pom.xml, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/mapper/ConditionsOfJoiningMapperTest.java
To prevent errors such as
```
Caused by:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "syncedAt" (class
com.transformuk.hee.tis.tcs.api.dto.ConditionsOfJoiningDto), not marked as ignorable (3 known properties: "version", "programmeMembershipUuid", "signedAt"])
```
`syncedAt` is used to record when the record is re-synced to TSS, it should always be null en-route to TIS.
TIS21-4714: Sync CoJ back from TIS to TSS
=> fix: allow unknown properties for CoJ json

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
When a record is filtered out by traineeInfoForConnection.sql (null/UNKNOWN/NA gmc number or dummy role), this PR will still export a dto with only tisPersonId to Reval ES (a queue which is listened by Integration service).
The following PR is https://github.com/Health-Education-England/tis-revalidation-integration/pull/443
TIS21-5100
=> feat:export dto to Reval only with tcsPersonId

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidatorTest.java
1. FieldR `FundingType.academic` has been renamed to `FundingType.allowDetails` in Reference service.
2. Funding type "Other" has been enabled to allow Details via flyway script in Reference servie.
TIS21-4875
depends on: https://github.com/Health-Education-England/TIS-REFERENCE/pull/309
=> feat:use allowDetails to check fundingType

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/DesignatedBodyMapper.java
The old dbc mapper is not needed as the GMC updated their test env using new prod dbcs.
TIS21-4657
=> chore:remove old dbc mapper on stage

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/PostFundingResource.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostFundingResourceIntTest.java
The following PR is https://github.com/Health-Education-England/TIS-GENERIC-UPLOAD/pull/236
1. I couldn't find any clue the endpoints `/post-fundings/XXX` are used in the frontend UI.
2. In person validator, we separate the endpoint for bulk upload to a patch API, and for frontend endpoints we return a `MethodArgumentNotValidException`. But we didn't do this way in that way. I'm not very sure if I should create a new endpoin like what we did for person validator.
TIS21-5384
=> feat:add validation to PostFunding Update

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImplTest.java
This is very belt and braces because of it shouldn't have happened. We should not have ended up with a  DataAccessEXception. We catch that but also check the returned ProgrammeMembership.
NO-CARD: Catch-up time
=> fix: catch additional exceptions

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidatorTest.java
This validator is currently used for bulk upload PostFunding Update validation. And we have to allow user input funding typ to be case insensitive.
TIS21-5384
=> fix:make fundingType case insensitive in PostFundingValidator

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidator.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/GdcDetailsValidator.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/GmcDetailsValidator.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonalDetailsValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/GdcDetailsResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/GmcDetailsResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidatorTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/GdcDetailsValidatorTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/GmcDetailsValidatorTest.java
A bulk upload issue was caused by 2 nationalities found for nationality name `Filipino`, so we set one of them to inactive in Reference. 
However, in PersonDetailValidator.validate(), we don't apply the filter to only get current values. 
And after a chat with James, we believe that `currentOnly=true` should be applied for all of the validators.
https://hee-nhs-tis.slack.com/archives/C03GBMYGZD4/p1713862211313339?thread_ts=1713783032.319379&cid=C03GBMYGZD4
TIS-SHED
=> fix:set currentOnly=true for person validators

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImplTest.java
To fix issue with missing PM causing infinite message processing as described
https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1722243933162119
(There are other places in the code that use getOne() but I think in a safe manner because they immediately retrieve the object.)
NO-TICKET
=> fix: CoJ find-PM code refactor

tcs-api/pom.xml, tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PostFundingDTO.java, tcs-client/pom.xml, tcs-persistence/pom.xml, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostValidatorTest.java
Given a user has the correct permissions
When they add or update a post funding record on the front end
Then Funding.StartDate must not be NULL
Given a user has the correct permissions
When they add or update a post funding record on the front end
Then if Funding.EndDate is not null then Funding.EndDate must not equal or be before Funding.StartDate
TIS21-5892
=> Feat add validation funding dates

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/TrainingNumberService.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostValidatorTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImplTest.java
The programme membership DTO has a legacy TrainingNumber field which does not get popualted.
Update the TrainingNumberService to allow calculation and population of TrainingNumbers in to a list of programme memberships. Update the ProgrammeMembershipService to call the new TrainingNumber population when fetching PMs to be displayed in Admins UI.
TIS21-6375
TIS21-6378
=> feat(ntn): populate NTN in PM data

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImplTest.java
The training number service is throwing an error when the parent organization can not be calculated. When there is any failure it should be caught and ignored so that the programme data can still be returned without the NTN/DRN populated.
TIS21-6375
=> fix: training number generation throwing error

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImplTest.java
There are records for GMC Details where the GMC Number is null. This commit treats GMC Details with a null GMC Number as no GMC Details.
TIS21-6425: Generate NTN for Dentists with a "null" GMC Number
=> fix: Generate dentist NTNs more reliably

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/PersonElasticSearchService.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/strategy/ProgrammeBasedFilterStrategy.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/strategy/RoleBasedFilterStrategy.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/strategy/TrustRoleBasedFilterStrategy.java
fix the programme filter when the user is assigned programmes, and refactor `searchForPage` method to remove duplicate codes.
1. added the columnFilter to `RoleBasedFilterStrategy.getFilter`, because when we apply the programmeId filter, we need to check if the programmeMembershipStatus filter is also applied. And currently, on the UI, we can only select either CURRENT or FUTURE, not both of them.
2. resume a `general programmeMembership.status filter` in `searchForPage` method in case no programmeId or programmeName filters are applied
3. tested locally under both scenarios if the user is assgined any programmes or not. I tried to set up some unit tests, but it asked for token in the context. For integration tests, we haven't properly set up an ES, so I finally gave up.
TIS21-6359
=> fix:the programme filter when the user is assigned programmes

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/PersonElasticSearchService.java
Previously this filter didn't work, and last iteration we added it back, which resulted in some users who don't have programme admin/observers roles not able to see person records which don't have any active programme memberships. So we decided to take it off as a patch to resume this functionality to be the same as before.
However, the programme membership filter doesn't work well and has to be reviewed in the future.
Tested locally.
TIS21-6359
=> fix:remove the outer programmeMembership status filter

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/config/KeycloakConfig.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/config/ReferenceClientProdConfig.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/config/TrustAdminConfig.java
The GMC Validator checks the given GMC status against the reference service to check if the value is valid. However, calls to the erference service use the current user's authentication token. As the new GMC update is received via RabbitMQ there is no authenticated user to provide a token.
Update ReferenceClientProdConfig to use a machine user token instead of requiring an actual user token.
TIS21-6292
TIS21-6479
=> fix: use machine user to call reference

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/GmcDetailsValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/GmcDetailsValidatorTest.java
The GMCDetailsValidator throws a `MethodArgumentNotValidException` when the validation fails, however the `parameter` field is incorrectly set to `null`.
This results in a `NullPointerException` when later trying to log the exception, which stops the exception being wrapped in a `AmqpRejectAndDontRequeueException`. The failure to wrap the exception means that RabbitMQ cannot send the failure to a DLQ and it is queued indefinitely.
Update the GMCDeailsValidator so that the `MethodParameter` is populated correctly.
A `NoSuchMethodException` must be handled, but will never happen unless the validate method is renamed without updating the declared method name. In this case the new unit test will fail, so it can never go live, but a runtime exception is thrown as a last resort to ensure that …
=> fix: construct proper exception for GMC validation

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/PostMapper.java
=> fix: include fundingReason in PostMapper

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResource.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java
if the trainee has a no linked forms the service will receive an empty array which was causing the app to be unable to load the forms list
=> refactor: add required handling of an empty array

tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeResource.java
Tested locally uploading "Post Creation" templates that use this endpoint via. the client.
The TCS client and UI are the only known usages.
----
Clients usually treat a 302 as a redirect.
No existing use of a 302 response status was found.
Also refactoring use of Collections.
Preferring JDK classes and purpose-built utility libraries. Apache Commons allows replacing negation for readability.
TIS21-6687: Building User Management via Admins UI
=> refactor: always respond ok for programmes search

tcs-service/Dockerfile
Tasks appear to be hitting a ceiling at 42% of RAM available. This has means the earlier memory increase is less effective. Adding the maximum size improves the ability to autoscale on memory.
TIS21-6834: Optimise JVM memory use
=> chore: Define max JVM memory

.github/workflows/ci-cd-workflow.yml
Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of actions/upload-artifact or actions/download-artifact. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
NO-CARD: Getting notified by cicd error
=> chore: upgrade Github actions

tcs-persistence/pom.xml, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/CurriculumMembershipRepository.java, tcs-persistence/src/test/java/com/transformuk/hee/tis/tcs/service/repository/CurriculumMembershipRepositoryIntTest.java, tcs-persistence/src/test/resources/scripts/curriculumMembership.sql, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/CurriculumMembershipValidator.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/CurriculumMembershipValidatorTest.java
1. Unexpected errors we sometimes have in bulk upload might result in the failure of the whole file. It would be hard to tell which records have already been created. So I added the duplicate validation. When users retry cm bulk create, the errors will tell them all the existing ones.
2. From a business perspective, there is not a case to have the exactly the same CM though (James said at least that he could think of). It would probably be useful to prevent duplicate CMs being created. If we don't, we would then probably need to develop a bulk CM delete
TIS21-3822
=> feat: add duplicate validation on CurriculumMembershipValidator

tcs-client/pom.xml, tcs-client/src/main/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImpl.java, tcs-client/src/test/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImplTest.java
Since findGmcDetailsIn() actually uses GMC numbers to search by, not ids. tis-sync PR to use this new client function to follow.
TIS21-6639
=> feat: get GMC by id

tcs-persistence/pom.xml, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/Post.java, tcs-service/pom.xml
When we’re trying to delete a row from the Post table, there are related rows in the PostTrust table that have a foreign key reference (postId). It is okay we delete the related rows in the PostTrust table when delete the Post.
TIS21-7021
=> fix: delete related post trusts against the post

tcs-persistence/pom.xml, tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/PostRepository.java, tcs-persistence/src/test/java/com/transformuk/hee/tis/tcs/service/repository/PostRepositoryTest.java, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/PostServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/PostServiceImplTest.java
In the Post table we have the following triggers
Target	Post (newPostId → id)
On Update	RESTRICT
On Delete	RESTRICT
Target	Post (oldPostId → id)
On Update	RESTRICT
On Delete	RESTRICT
So when we try to delete a Post it throws error.
TIS21-7021
=> Bug fix - clear old and new post id foreign key references

tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/ProgrammeMembershipRepository.java, tcs-service/pom.xml, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/exception/DuplicateCurriculumMembershipException.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/exception/ExceptionTranslator.java, tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java, tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java
- Implemented the ACs mentioned in the ticket
- Added two tests for reusing curriculum memberships. 
- All the comments in the draft pr are considered
- Input and Output data have been checked
- Different combinations of PM and CMs were tested locally
- patch test is also considered
TIS21-7457
=> test: add tests for reusing cm
