Health-Education-England/TIS-TCS

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidatorTest.java
1. refactor the existence validation of FundingType.
2. release validation to allow acdemic fundingType to have info(funding details).
3. fix tests.
TIS21-437
> feat: enable academic fundingTypes to have info(details)

- tcs-service/pom.xml
- tcs-service/src/main/resources/db/migration/data/hee/V4.11__updatePersonStatusUsingProgrammeTIS21_487.sql
TIS21-487: Set training status retrospectively
> chore: correct training status for trainees

- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/ContactDetailsRepository.java
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/ContactDetailsResource.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/PersonResource.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/ContactDetailsValidatorTest.java
[TIS21_2284](https://hee-tis.atlassian.net/browse/TIS21-2284)
When updating the person record, the current one needs to be excluded for validation.
> feat: add validation to email to make unique

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PlacementDetailsDTO.java
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PlacementEsrEventDto.java
- tcs-persistence/pom.xml
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/PlacementServiceImpl.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/PlacementEsrEventDtoMapper.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/PlacementServiceImplTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/mapper/PlacementEsrEventDtoMapperTest.java
We've already had a `EsrEvent` set in PlacementSummaryDTO which used by the UI to show ESR status on Person-Placements list.
This ticket is to add the same `EsrEvent` set in PlacementDetailDTO for Placement Detail pages.
TIS21-174
> feat: add EsrEvent in PlacementDetailDTO

- .github/workflows/ci-cd-workflow.yml
- pom.xml
- tcs-api/pom.xml
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-service/pom.xml
Add a step to the CI/CD workflow to publish artifacts to CodeArtifact.
Bump all patch versions to simulate new artifacts for verification
purposes.
TIS21-2495
> chore: Add deploy/publish step to CI/CD workflow

- .github/workflows/ci-cd-workflow.yml
> chore: skip tests when publishing artifacts

- tcs-service/pom.xml
> chore: skip deploy of tcs-service

- .github/workflows/ci-cd-workflow.yml
- .github/workflows/pr-analysis.yml
- README.md
> chore: rename master to main

- tcs-client/pom.xml
- tcs-service/pom.xml
> chore: bump tis_security_jwt version

- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/ProgrammeMembershipRepository.java
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
> fix: change reval CCT to curriculum end day

- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PlacementValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PlacementResourceIntTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PlacementValidatorTest.java
1. There's only 1 primary specialty allowed and it's required. There's only 1 sub specialty allowed.
2. All the specialties should exists in Specitly table.
3. If the sub specialty is specified, it should be from the parent post.
TIS21-2356
> feat: add validation of Placement Specialties

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/RevalidationMessageListener.java
TIS21-2669: Filter Recommendations with ES - Rebuild ES Job
> chore: set ack mode for reval queue listener

- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/Person.java
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/CurriculumMembershipRepository.java
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/event/CurriculumMembershipCreatedEvent.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/event/CurriculumMembershipDeletedEvent.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/event/CurriculumMembershipSavedEvent.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/listener/person/CurriculumMembershipEventListener.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/listener/person/TrainingNumberElasticSearchEventListener.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/listener/person/CurriculumMembershipEventListenerTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
> feat: event listeners use CurriculumMembership

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/PostResource.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResource2Test.java
To bring into line with https://github.com/Health-Education-England/TIS-EsrInboundDataWriterService/pull/209
TIS21-2638
> fix: correct Post Esr Event endpoint URL

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonValidator.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/RightToWorkValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PersonValidatorTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/RightToWorkValidatorTest.java
add validation checking against db for visa date validation
Tis21 505
> Tis21 505 improve visa validation

- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/RightToWorkValidator.java
Hotfix for ticket TIS21-505
NPE encountered when users updated either the VisaValidTo date or the VisaIssued date when none present in the DB
> Fix: Handle NPEs

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/ProgrammeMembershipValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java
> Add validation to programme start and finish date

- tcs-client/pom.xml
try if pushing to artifact works.
no-ticket
> chore: bump version of tcs-client

- tcs-service/src/main/resources/db/migration/data/hee/V4.23__deleteHiddenProgrammeMemberships.sql
TIS21-3512: Query ProgrammeMemberships similar to ghost ones
> chore: delete invisible Programme Memberships

- tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql
> feat:modify sql to use combined current programmes

- .aws/tis-tcs-nimdta.json
- .aws/tis-tcs-preprod.json
- .aws/tis-tcs-prod.json
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/RevalidationMessageListener.java
- tcs-service/src/main/resources/config/application-local.yml
- tcs-service/src/main/resources/config/application.yml
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/message/RevalidationMessageListenerTest.java
- tcs-service/src/test/resources/config/application.yml
> feat:add currentPmSync listener

- tcs-service/src/main/resources/db/migration/data/hee/V4.24__delete_duplicatedPersonRecord.sql
Data recorded against tis id: 265154
TIS21-4266: Merge Trainee Record
> chore: delete duplicated person record

- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/DesignatedBodyMapper.java
2 DBCs have been modified in stage but not production.
TIS21-4289: Investigate GMC DBC changes
> feat: use alternative designated body mapper

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/DesignatedBodyMapper.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeResourceIntTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/mapper/DesignatedBodyMapperTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
> feat:update dbc mapper

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/ConnectionInfoDto.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
TIS21-4194:TCS, Integration Service & Connection Service - Remove field connectionStatus
> chore: remove references to unused field connectionStatus for reval CDC

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/ConditionsOfJoiningDto.java
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/ProgrammeMembershipDTO.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListener.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/ConditionsOfJoiningService.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImpl.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/CurriculumMembershipMapper.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapper.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/listener/person/TrainingNumberElasticSearchEventListenerTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListenerTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceImplTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ConditionsOfJoiningServiceTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/mapper/CurriculumMembershipMapperTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapperTest.java
TIS21-4514: Back-end API for CoJ status to support Admins-UI
> feat: add CoJ to Programme Membership Dto

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/CurriculumMembershipMapper.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapper.java
refactor some small bits of programme membership and curriculum membership mappers
TIS21-2403
> refactor:mappers of programme/curriculum membersips

- .aws/tis-tcs-nimdta.json
- .aws/tis-tcs-preprod.json
- .aws/tis-tcs-prod.json
- tcs-service/pom.xml
- tcs-service/src/main/resources/config/application.yml
- tcs-service/src/main/resources/logback-spring.xml
Sentry configuration has been added.
TIS21-4560
> feat: add sentry configuration

- tcs-service/pom.xml
Lost unintentionally as part of a merge commit
NO-CARD: fixing deployment
> revert(deps): revert removal of senty lib

- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/aop/auditing/AuditingAspect.java
This is a bug that follows modifying the method to get ProgrammeMembership by either a `Long` or `UUID` id.
We've got some divergence in how the service is structured. "CurriculumMemberships" are managed via a "ProgrammeMembershipResource". We haven't agreed how to properly fix this.
Taking a chance local sonar is more cautious than sonarcloud for NPE so might need to push something extra for that.
I started on a test but mocking the static method requires an upgrade of Mockito, which we get based on the version of spring.
NO-CARD: fixing deployment
> feat: skip auditing when no get method exists

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/CurriculumMembershipMapper.java
for deprecated fields.
TIS21-2403
> refactor:remove parallel saving to CM

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/RevalidationResource.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/RevalidationResourceTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImplTest.java
> fix:NPE for getConnectionDetailByGmcId

- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/RevalidationResource.java
> chore: add comment to currently unused endpoint

- tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql
Adding a condition doesn't make too much difference on the performance.
TIS21-4662
> fix:exclude non-breaking space records for Reval

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/RevalidationServiceImpl.java
> fix: correctly get current placement grade from sql

- .github/workflows/pr-analysis.yml
This reverts commit 236510b589459cf2c12d419e5d31bc4a9d976daa.
> Revert "build: add missing permissions"

- .aws/tis-tcs-nimdta.json
- .aws/tis-tcs-preprod.json
- .aws/tis-tcs-prod.json
- tcs-service/src/test/resources/config/application.yml
This reduces the load on the profile service.
That is balanced with the need to expire removed users.
TIS21-4943: ESR processing affected by profile availability
> chore: increase TTL of user profile cache

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/ProgrammeMembershipValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceIntTest.java
> fix:programme membership bulk update err messages

- tcs-persistence/src/main/resources/queries/traineeInfoForConnection.sql
> feat:filter out N/A(NA) gmc numbers for Reval

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PostFundingDTO.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/PostFunding.java
- tcs-service/pom.xml
- tcs-service/src/main/resources/db/migration/schema/V4.27__add_fundingsubtype_to_postfunding.sql
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidatorTest.java
TIS21-5381: Modify PostFunding Table to store FundingSubType uuid
> feat: add fundingSubType field to PostFunding

- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/PostFunding.java
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/PostMapper.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/mapper/PostMapperTest.java
so frontend Post page will be able to create/update/show postfundings with fundingSubType
TIS21-5634
> fix:postFundingMapper for PostResource

- .github/workflows/ci-cd-workflow.yml
- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PostFundingDTO.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/PostFunding.java
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/PostMapper.java
- tcs-service/src/main/resources/db/migration/schema/V4.28__rename_fundingsubtype_to_fundingsubtypeid_postfunding.sql
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidatorTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/mapper/PostMapperTest.java
and upgrade java 11 to 17 in cicd workflow
TIS21-5634
> fix:rename fundingSubType to fundingSubTypeId in postFunding

- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/PostFunding.java
- tcs-service/pom.xml
> fix:the column name for PostFunding.fundingSubTypeId

- tcs-client/pom.xml
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidator.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/PostFundingValidatorTest.java
> feat:add fundingSubType validation for PostFunding

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PostDTO.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/Post.java
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/PostMapper.java
- tcs-service/src/main/resources/db/migration/schema/v4.30__add_fundingstatus_field_to_post_and_populate.sql
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResource2Test.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostResourceIntTest.java
TIS21-5808: Add a new field fundingStatus in Post
> feat: add fundingStatus field to Post and initialise values with flyway

- tcs-service/pom.xml
- tcs-service/src/main/resources/db/migration/schema/V4.31__drop_not_null_constraint_for_fundingstatus.sql
TIS21-5808: Add a new field fundingStatus in Post
> fix: remove fundingstatus not null constraint

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImpl.java
Update TrainingNumberService to make some small refactorings based on PR feedback.
TIS21-6375
TIS21-6378
> refactor: training number generation

- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImpl.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/TrainingNumberServiceImplTest.java
> fix: TSD prefix for military training numbers

- .aws/tis-tcs-nimdta.json
- .aws/tis-tcs-preprod.json
- .aws/tis-tcs-prod.json
- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/GmcDetailsDTO.java
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/validation/TraineeUpdate.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/event/GmcDetailsProvidedEvent.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListener.java
- tcs-service/src/main/resources/config/application-local.yml
- tcs-service/src/main/resources/config/application.yml
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/message/TraineeMessageListenerTest.java
- tcs-service/src/test/resources/config/application.yml
Update a trainee's GMC details when a GmcDetailsProvided event is received.
Perform validation on both the event and updated GMC details to ensure that the new details are valid.
TIS21-6292
TIS21-6479
> feat: update GMC details when provided by trainee

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/PostFundingDTO.java
- tcs-client/pom.xml
- tcs-persistence/pom.xml
- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/PostFunding.java
- tcs-service/pom.xml
- tcs-service/src/main/resources/db/migration/schema/V4.37__add_fundingreasonuuid_to_postfunding.sql
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/PostFundingResourceIntTest.java
TIS21-6498: Add fundingReason field to PostFunding in TCS
> feat: add fundingReason field to PostFunding Classes

- tcs-client/pom.xml
> chore: bump tcs-client pom version

- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/repository/ProgrammeMembershipRepository.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResource.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/ProgrammeMembershipService.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImpl.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/ProgrammeMembershipResourceTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/ProgrammeMembershipServiceImplTest.java
I think this could work - and it saves you having to set up a ProgrammeMembershipRepository test for your new method ;)
> fix: use existing repository method

- tcs-api/pom.xml
- tcs-api/src/main/java/com/transformuk/hee/tis/tcs/api/dto/CurriculumMembershipDTO.java
- tcs-client/pom.xml
- tcs-client/src/main/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImpl.java
- tcs-client/src/test/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImplMockTest.java
- tcs-client/src/test/java/com/transformuk/hee/tis/tcs/client/service/impl/TcsServiceImplTest.java
- tcs-persistence/pom.xml
- tcs-service/pom.xml
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/CurriculumMembershipResource.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/api/validation/CurriculumMembershipValidator.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/CurriculumMembershipService.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/impl/CurriculumMembershipServiceImpl.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/CurriculumMembershipMapper.java
- tcs-service/src/main/java/com/transformuk/hee/tis/tcs/service/service/mapper/ProgrammeMembershipMapper.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/CurriculumMembershipResourceTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/api/validation/CurriculumMembershipValidatorTest.java
- tcs-service/src/test/java/com/transformuk/hee/tis/tcs/service/service/impl/CurriculumMembershipServiceTest.java
Add a CurriculumMembership resource to handle the curriculum membership only requests. The only API currently is for bulk curriculum membership creates.
> Feat: curriculum membership api TIS21-3822

- tcs-service/src/main/resources/db/migration/schema/V4.38__repopulate_post_fundingStatus.sql
Prod failed due to error "You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column".
This repopulation doesn't affect other existing fields on Post table.
TIS21-6574
> fix: the scripts to repopulate post fundingStatus

- tcs-persistence/src/main/java/com/transformuk/hee/tis/tcs/service/model/Specialty.java
> fix: change specialty type fetch eager for audit purpose
